Rebuild for updated pcre2
The package fails to install in Rawhide at the moment with:

DEBUG util.py:444:  Error:
DEBUG util.py:444:   Problem: package util-linux-2.37-2.fc35.x86_64 requires util-linux-core = 2.37-2.fc35, but none of the providers can be installed
DEBUG util.py:444:    - conflicting requests
DEBUG util.py:444:    - nothing provides libpcre2-posix.so.2()(64bit) needed by util-linux-core-2.37-2.fc35.x86_64

This is my attempt to see if I can fix this with a simple rebuild.  If
not I will file a bug.